# BuildingAnRPackage
Coursera Assignment

## What i did

1. Creating a Git Project
  + Create a [public repository](https://github.com/ZhangHaoquan/BuildingAnRPackage)
  + Create a new project from RStudio in a local repository
  + Add, Commit and Push the project folder to the remote repository
  + devtools::use_mit_license adds a license to prevent warnings from checks later

2. Package Core Functions
  + Data is gathered from [US National Highway Traffic Safety Administration](https://www.nhtsa.gov/research-data/fatality-analysis-reporting-system-fars#)
  + The dataset of interest is provide by [Fatality Analysis Reporting System (FARS)](https://www.nhtsa.gov/research-data/fatality-analysis-reporting-system-fars#)
  + The official FTP site to download the data can be found [here](ftp://ftp.nhtsa.dot.gov/fars/)
  + Downloaded data are placed in the same folder as the vignette to power the markdown
  + Add fars_function.R along with the relevant roxygen2
  + Learn roxygen tags via these links:
    * [link_1](https://cran.r-project.org/web/packages/roxygen2/vignettes/formatting.html}{RStudio Formatting})
    * [link_2](https://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html)
  + devtools::document automatically generates the NAMESPACE in the root folder
  + devtools::document also generates and the documentation files in the man folder

3. Setting up testing framework
  + devtools::use_testthat sets up testing infrastructure, creating tests/testthat.R and tests/testthat/
  + devtools::use_test sets creates tests/testthat/test-<name>.R and opens it for editing.
  + devtools::test executes the tests
  + Implement a test for make_filename.R functions
  
4. Create a Vignette
  + devtools::use_vignette creates a sub-directory and adds a vignette markdown document there for edit

5. Check build
  + devtools::check builds the package applying the same rigous as travis
  + devtools::check_failures reads the check output folder and suggests possible areas of failure
  + Check that R CMD check results has no errors
  
### Prerequisites

What things you need to install the software and how to install them

```
Give examples
```

### Installing

A step by step series of examples that tell you have to get a development env running

Say what the step will be

```
Give the example
```

And repeat

```
until finished
```

End with an example of getting some data out of the system or using it for a little demo

## Running the tests

Explain how to run the automated tests for this system

### Break down into end to end tests

Explain what these tests test and why

```
Give an example
```

### And coding style tests

Explain what these tests test and why

```
Give an example
```

## Deployment

Add additional notes about how to deploy this on a live system

## Built With

* [Dropwizard](http://www.dropwizard.io/1.0.2/docs/) - The web framework used
* [Maven](https://maven.apache.org/) - Dependency Management
* [ROME](https://rometools.github.io/rome/) - Used to generate RSS Feeds

## Contributing

Please read [CONTRIBUTING.md](https://gist.github.com/PurpleBooth/b24679402957c63ec426) for details on our code of conduct, and the process for submitting pull requests to us.

## Versioning

We use [SemVer](http://semver.org/) for versioning. For the versions available, see the [tags on this repository](https://github.com/your/project/tags). 

## Authors

* **Billie Thompson** - *Initial work* - [PurpleBooth](https://github.com/PurpleBooth)

See also the list of [contributors](https://github.com/your/project/contributors) who participated in this project.

## License

This project is licensed under the MIT License - see the [LICENSE.md](LICENSE.md) file for details

## Acknowledgments

* Hat tip to anyone who's code was used
* Inspiration
* etc
